
version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    # volumes:
    #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - webnet

  # rabbitmq:
  #   image: rabbitmq
  #   networks:
  #     - webnet

  redis:
    image: redis
    networks:
      - webnet

  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: 1@m.
      POSTGRES_USER: postgres
      POSTGRES_DB: paymentAPI
    ports:
      - "5431:5432"

  web:
    image: mock-payment-api
    depends_on:
      - "rabbitmq"
      - "redis"
      - "db"
    ports:
      - "2000:2000"
    networks:
      - webnet
    environment:
      rabbitMQ_HOST: rabbitmq
      DB_HOST: db
      REDIS_HOST: redis
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- npm start'

networks:
  webnet:
    driver: bridge